Models/Bug.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TaskBugTracker.Models
{
    public class Bug : Assignment
    {
        public int BugId { get; set; }

        [Required]
        [MaxLength(20)]
        [Column(TypeName = "varchar(20)")]
        public string Priority { get; set; } = "Low";

        [ForeignKey("Project")]
        public int ProjectId { get; set; }
        public Project Project { get; set; }
    }
}

Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TaskBugTracker.Models
{
    public class Project : Assignment
    {
        //public Project()
        //{
        //    Tasks = new List<Models.Task>();
        //    Bugs = new List<Bug>();
        //}
        public int ProjectId { get; set; }

        public IEnumerable<Models.Task> Tasks { get; set; }

        public IEnumerable<Models.Bug> Bugs { get; set; }

    }
}

Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TaskBugTracker.Models
{
    public class Task : Assignment
    {
        public int TaskId { get; set; }

        [Required]
        [MaxLength(20)]
        [Column(TypeName = "varchar(20)")]
        public string Priority { get; set; } = "Low";

        [ForeignKey("Project")]
        public int ProjectId { get; set; }
        public Project Project { get; set; }
    }
}

ViewModels/ProjectViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TaskBugTracker.ViewModels
{
    public class ProjectViewModel : AssignmentViewModel
    {
        public int ProjectId { get; set; }
        public IEnumerable<Models.Task> Tasks { get; set; }
        public IEnumerable<Models.Bug> Bugs { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TaskBugTracker.Data;
using TaskBugTracker.Data.FileManager;
using TaskBugTracker.Data.Repository;
using TaskBugTracker.Models;

namespace TaskBugTracker.Controllers
{
    public class HomeController : Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;

        public HomeController(IRepository repo, IFileManager fileManager)
        {
            _repo = repo;
            _fileManager = fileManager;
        }

        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "Title_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.StatusSortParm = sortOrder == "Status" ? "Status_desc" : "Status";

            var projects = from s in _repo.GetAllProjects()
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                projects = projects.Where(s => s.Title.Contains(searchString)
                                       || s.Description.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "Title_desc":
                    projects = projects.OrderByDescending(s => s.Title);
                    break;
                case "Date":
                    projects = projects.OrderByDescending(s => s.LastModified);
                    break;
                case "Date_desc":
                    projects = projects.OrderBy(s => s.LastModified);
                    break;
                case "Status":
                    projects = projects.OrderBy(s => s.Status);
                    break;
                case "Status_desc":
                    projects = projects.OrderByDescending(s => s.Status);
                    break;
                default:
                    projects = projects.OrderBy(s => s.Title);
                    break;
            }
            return View(projects.ToList());
        }

        public IActionResult Project(int id, string taskSortOrder, string bugSortOrder)
        {
            var project = _repo.GetProject(id);

            ViewBag.TitleSortParm = String.IsNullOrEmpty(taskSortOrder) ? "Title_desc" : "";
            ViewBag.DateSortParm = taskSortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.PrioritySortParm = taskSortOrder == "Priority" ? "Priority_desc" : "Priority";
            ViewBag.StatusSortParm = taskSortOrder == "Status" ? "Status_desc" : "Status";

            ViewBag.TitleSortParm = String.IsNullOrEmpty(bugSortOrder) ? "Title_desc" : "";
            ViewBag.DateSortParm = bugSortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.PrioritySortParm = bugSortOrder == "Priority" ? "Priority_desc" : "Priority";
            ViewBag.StatusSortParm = bugSortOrder == "Status" ? "Status_desc" : "Status";

            var tasks = from t in _repo.GetAllTasks(id)
                        select t;

            switch (taskSortOrder)
            {
                case "Title_desc":
                    tasks = tasks.OrderByDescending(t => t.Title);
                    break;
                case "Date":
                    tasks = tasks.OrderByDescending(t => t.LastModified);
                    break;
                case "Date_desc":
                    tasks = tasks.OrderBy(t => t.LastModified);
                    break;
                case "Priority":
                    tasks = tasks.OrderBy(t => t.Priority);
                    break;
                case "Priority_desc":
                    tasks = tasks.OrderByDescending(t => t.Priority);
                    break;
                case "Status":
                    tasks = tasks.OrderBy(t => t.Status);
                    break;
                case "Status_desc":
                    tasks = tasks.OrderByDescending(t => t.Status);
                    break;
                default:
                    tasks = tasks.OrderBy(t => t.Title);
                    break;
            }

            project.Tasks = tasks;

            var bugs = from b in _repo.GetAllBugs(id)
                        select b;

            switch (taskSortOrder)
            {
                case "Title_desc":
                    bugs = bugs.OrderByDescending(b => b.Title);
                    break;
                case "Date":
                    bugs = bugs.OrderByDescending(b => b.LastModified);
                    break;
                case "Date_desc":
                    bugs = bugs.OrderBy(b => b.LastModified);
                    break;
                case "Priority":
                    bugs = bugs.OrderBy(b => b.Priority);
                    break;
                case "Priority_desc":
                    bugs = bugs.OrderByDescending(b => b.Priority);
                    break;
                case "Status":
                    bugs = bugs.OrderBy(b => b.Status);
                    break;
                case "Status_desc":
                    bugs = bugs.OrderByDescending(b => b.Status);
                    break;
                default:
                    bugs= bugs.OrderBy(b => b.Title);
                    break;
            }

            project.Bugs = bugs;
            return View(project);
        }

        public IActionResult Task(int id)
        {
            var task = _repo.GetTask(id);
            return View(task);
        }

        public IActionResult Bug(int id)
        {
            var bug = _repo.GetBug(id);
            return View(bug);
        }

        [HttpGet("/Image/{image}")]
        public IActionResult Image(string image)
        {
            var mime = image.Substring(image.LastIndexOf('.')+1);
            return new FileStreamResult(_fileManager.ImageStream(image), $"image/{mime}");
        }
    }
}

Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TaskBugTracker.Data.FileManager;
using TaskBugTracker.Data.Repository;
using TaskBugTracker.Models;
using TaskBugTracker.ViewModels;

namespace TaskBugTracker.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;

        public PanelController(IRepository repo, IFileManager fileManager)
        {
            _repo = repo;
            _fileManager = fileManager;
        }

        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "Title_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.StatusSortParm = sortOrder == "Status" ? "Status_desc" : "Status";

            var projects = from s in _repo.GetAllProjects()
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                projects = projects.Where(s => s.Title.Contains(searchString)
                                       || s.Description.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "Title_desc":
                    projects = projects.OrderByDescending(s => s.Title);
                    break;
                case "Date":
                    projects = projects.OrderByDescending(s => s.LastModified);
                    break;
                case "Date_desc":
                    projects = projects.OrderBy(s => s.LastModified);
                    break;
                case "Status":
                    projects = projects.OrderBy(s => s.Status);
                    break;
                case "Status_desc":
                    projects = projects.OrderByDescending(s => s.Status);
                    break;
                default:
                    projects = projects.OrderBy(s => s.Title);
                    break;
            }
            return View(projects.ToList());
        }

        [HttpGet]
        public IActionResult EditProject(int? id)
        {
            if (id == null)
            {
                return View(new ProjectViewModel());
            }
            else
            {
                var project = _repo.GetProject((int)id);
                return View(new ProjectViewModel
                    {
                        ProjectId = project.ProjectId,
                        Title = project.Title,
                        Description = project.Description,
                        CurrentImage = project.Image,
                        Status = project.Status,
                        Tasks = project.Tasks,
                        Bugs = project.Bugs

                    }
                );
            }

        }

        [HttpGet]
        public IActionResult EditTask(int projectId, int? id)
        {
            if (id == null)
            {
                return View(new TaskBugViewModel 
                {
                    ProjectId = projectId
                });
            }
            else
            {
                var task = _repo.GetTask((int)id);
                return View(new TaskBugViewModel
                {
                    Id = task.TaskId,
                    ProjectId = task.ProjectId,
                    Title = task.Title,
                    Description = task.Description,
                    CurrentImage = task.Image,
                    Status = task.Status,
                    Priority = task.Priority,
                });
            }

        }

        [HttpGet]
        public IActionResult EditBug(int projectId, int? id)
        {
            if (id == null)
            {
                return View(new TaskBugViewModel
                {
                    ProjectId = projectId
                });
            }
            else
            {
                var bug = _repo.GetBug((int)id);
                return View(new TaskBugViewModel
                {
                    Id = bug.BugId,
                    ProjectId = bug.ProjectId,
                    Title = bug.Title,
                    Description = bug.Description,
                    CurrentImage = bug.Image,
                    Status = bug.Status,
                    Priority = bug.Priority

                }
                );
            }

        }

        [HttpPost]
        public async Task<IActionResult> EditProject(ProjectViewModel vm)
        {
            var project = new Project
            {
                ProjectId = vm.ProjectId,
                Title = vm.Title,
                Description = vm.Description,
                Image = await _fileManager.SaveImage(vm.Image),
                Status = vm.Status,
                Tasks = vm.Tasks,
                Bugs = vm.Bugs
            };

            if (vm.Image == null)
                project.Image = vm.CurrentImage;
            else
                project.Image = await _fileManager.SaveImage(vm.Image);


            if (project.ProjectId > 0)
                _repo.UpdateProject(project);
            else
                _repo.AddProject(project);


            if (await _repo.SaveChangesAsync())
                return RedirectToAction("Index");
            else
                return View(project);

        }

        [HttpPost]
        public async Task<IActionResult> EditTask(TaskBugViewModel vm)
        {
            var task = new Models.Task
            {
                TaskId = vm.Id,
                ProjectId = vm.ProjectId,
                Title = vm.Title,
                Description = vm.Description,
                Image = await _fileManager.SaveImage(vm.Image),
                Status = vm.Status,
                Priority = vm.Priority
            };

            if (vm.Image == null)
                task.Image = vm.CurrentImage;
            else
                task.Image = await _fileManager.SaveImage(vm.Image);


            if (task.TaskId > 0)
                _repo.UpdateTask(task);
            else
                _repo.AddTask(task);


            if (await _repo.SaveChangesAsync())
                return RedirectToAction("Index", "Home");
            else
                return View(task);

        }

        [HttpPost]
        public async Task<IActionResult> EditBug(TaskBugViewModel vm)
        {
            var bug = new Bug
            {
                BugId = vm.Id,
                ProjectId = vm.ProjectId,
                Title = vm.Title,
                Description = vm.Description,
                Image = await _fileManager.SaveImage(vm.Image),
                Status = vm.Status,
                Priority = vm.Priority
            };

            if (vm.Image == null)
                bug.Image = vm.CurrentImage;
            else
                bug.Image = await _fileManager.SaveImage(vm.Image);


            if (bug.BugId > 0)
                _repo.UpdateBug(bug);
            else
                _repo.AddBug(bug);


            if (await _repo.SaveChangesAsync())
                return RedirectToAction("Index", "Home");
            else
                return View(bug);

        }

        [HttpGet]
        public async Task<IActionResult> RemoveProject(int id)
        {
            _repo.RemoveProject(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> RemoveTask(int id)
        {
            _repo.RemoveTask(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> RemoveBug(int id)
        {
            _repo.RemoveBug(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");

        }
    }
}

Views/Home/Bug.cshtml
@model Bug

@{ 
    ViewData["Title"] = Model.Title;
    ViewData["Description"] = Model.Description;
    ViewData["Keywords"] = "project tracker task bug progress programming code";
}

<div class="container">
    @if (!String.IsNullOrEmpty(Model.Image))
    {
        var image_path = $"/Image/{Model.Image}";
        string status_path = $"{Model.Status}.png";

        <div>
            <img class="project-img no-shadow" src="@image_path" height="200" />
            <img src="~/content/static/status/@status_path" style="width: 10px;" /> @Model.Status

        </div>
    }
    @Model.Title
    <div class="project-body">
        @Html.Raw(Model.Description)
        <hr>

        <div class="container">
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Panel" asp-action="EditBug" asp-route-projectId="@Model.ProjectId" asp-route-id="@Model.BugId">Edit Bug</a>
            }
            <hr>

            </div>
    </div>
</div>

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Components.Web
@model IEnumerable<Project>

@{
    ViewData["Title"] = "Home Page - Project Tracker";
    ViewData["Description"] = "Maintain the progress of your projects";
    ViewData["Keywords"] = "project tracker task bug progress programming code";
}

@using (Html.BeginForm())
{
    <p title="Search" style="padding-top: 20px; text-align: center;">
        @Html.TextBox("SearchString")
        <input class="fa-star" type="submit" value="Search" />
    </p>
}
<table>
    <tr>
        <th>Sort By:</th>
        <th>
            @Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.TitleSortParm }) |
        </th>
        <th>
            @Html.ActionLink("Last Modified", "Index", new { sortOrder = ViewBag.DateSortParm }) |
        </th>
        <th>
            @Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.StatusSortParm })
        </th>
    </tr>
</table>

<div class="cards-container">
    <div class="row" style="width: 100%;">
        @foreach (var project in Model)
        {
            var image_path = $"/Image/{project.Image}";
            var status_path = $"{project.Status}.png";
            <section class="col-lg-5 col-md-6 py-4">
                <div class="card small">
                    <a asp-controller="Home" asp-action="Project" asp-route-id="@project.ProjectId">
                        <img src="@image_path" class="card-img-top" />
                    </a>

                    <div class="card-body">
                        <h4 class="card-title" style="height: 30px; overflow-y: hidden">
                            <a asp-controller="Home" asp-action="Project" asp-route-id="@project.ProjectId">@project.Title</a>
                        </h4>
                        <div class="card-subtitle text-muted" style="height: 20px; overflow-y: hidden">
                            <h6>@project.Description</h6>
                        </div>

                        <small class="text-muted">Last Modified: @project.LastModified</small>

                        <p class="card-text text-muted">
                            <img src="~/content/static/status/@status_path" style="width: 10px;" /> @project.Status
                            

                        </p>
                    </div>
                </div>
            </section>

        }
    </div>
</div>

Views/Home/Project.cshtml
@model Project

@{ 
    ViewData["Title"] = Model.Title;
    ViewData["Description"] = Model.Description;
    ViewData["Keywords"] = "project tracker task bug progress programming code";
}

<div class="container">
    @if (!String.IsNullOrEmpty(Model.Image))
    {
        var image_path = $"/Image/{Model.Image}";
        string status_path = $"{Model.Status}.png";

        <div>
            <img class="project-img no-shadow" src="@image_path" height="200" />
            <img src="~/content/static/status/@status_path" style="width: 10px;" /> @Model.Status

        </div>
    }
    @Model.Title
    <div class="project-body">
        @Html.Raw(Model.Description)
        <hr>

        <div class="container">
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Panel" asp-action="EditTask" asp-route-projectId="@Model.ProjectId">New Task</a>
            }
            <h5>Tasks</h5>
            @if (Model.Tasks != null)
            {
                <table class="table">
                    <tr>
                        <th>
                            @Html.ActionLink("Title", "Project", new { taskSortOrder = ViewBag.TitleSortParm})
                        </th>
                        <th>
                            @Html.ActionLink("Last Modified", "Project", new { taskSortOrder = ViewBag.DateSortParm})
                        </th>
                        <th>
                            @Html.ActionLink("Priority", "Project", new { taskSortOrder = ViewBag.PrioritySortParm})
                        </th>
                        <th>
                            @Html.ActionLink("Status", "Project", new { taskSortOrder = ViewBag.StatusSortParm})
                        </th>
                    </tr>
                    @foreach (var task in Model.Tasks)
                    {
                        <tr>
                            <td>
                                <a asp-controller="Home" asp-action="Task" asp-route-id="@task.TaskId">@task.Title</a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => task.LastModified)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => task.Priority)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => task.Status)
                            </td>
                            <th>
                                <a asp-controller="Panel" asp-action="EditTask" asp-route-projectId="@Model.ProjectId" asp-route-id="@task.TaskId">Edit</a>
                                |
                                <a asp-controller="Panel" asp-action="RemoveTask" asp-route-projectId="@Model.ProjectId" asp-route-id="@task.TaskId">Remove</a>
                            </th>
                        </tr>
                    }
                </table>
            }
            else
            {
                <div>No Tasks</div>
            }
            <hr>

            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Panel" asp-action="EditBug" asp-route-projectId="@Model.ProjectId">New Bug</a>
            }
            <h5>Bugs</h5>
            @if (Model.Bugs != null)
            {
                <table class="table">
                    <tr>
                        <th>
                            @Html.ActionLink("Title", "Project", new { @*sortOrder = ViewBag.TitleSortParm*@})
                        </th>
                        <th>
                            @Html.ActionLink("Last Modified", "Project", new { @*sortOrder = ViewBag.DateSortParm*@})
                        </th>
                        <th>
                            @Html.ActionLink("Priority", "Project", new { @*sortOrder = ViewBag.DateSortParm*@})
                        </th>
                        <th>
                            @Html.ActionLink("Status", "Project", new { @*sortOrder = ViewBag.StatusSortParm*@})
                        </th>
                    </tr>

                    @foreach (var bug in Model.Bugs)
                    {
                        <tr>
                            <td>
                                <a asp-controller="Home" asp-action="Bug" asp-route-projectId="@Model.ProjectId" asp-route-id="@bug.BugId">@bug.Title</a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => bug.LastModified)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => bug.Priority)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => bug.Status)
                            </td>
                            <th>
                                <a asp-controller="Panel" asp-action="EditBug" asp-route-projectId="@Model.ProjectId" asp-route-id="@bug.BugId">Edit</a>
                                |
                                <a asp-controller="Panel" asp-action="RemoveBug" asp-route-projectId="@Model.ProjectId" asp-route-id="@bug.BugId">Remove</a>
                            </th>
                        </tr>
                    }
                </table>
            }
            else
            {
                <div>No Bugs</div>
            }
            <hr>

            </div>
    </div>
</div>

Views/Home/Task.cshtml
@namespace TaskBugTracker
@model Models.Task

@{ 
    ViewData["Title"] = Model.Title;
    ViewData["Description"] = Model.Description;
    ViewData["Keywords"] = "project tracker task bug progress programming code";
}

<div class="container">
    @if (!String.IsNullOrEmpty(Model.Image))
    {
        var image_path = $"/Image/{Model.Image}";
        string status_path = $"{Model.Status}.png";

        <div>
            <img class="project-img no-shadow" src="@image_path" height="200" />
            <img src="~/content/static/status/@status_path" style="width: 10px;" /> @Model.Status

        </div>
    }
    @Model.Title
    <div class="project-body">
        @Html.Raw(Model.Description)
        <hr>

        <div class="container">
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Panel" asp-action="EditTask" asp-route-projectId="@Model.ProjectId" asp-route-id="@Model.TaskId">Edit Task</a>
            }
            <hr>

            </div>
    </div>
</div>